[youtube-step1-무비] step1 통합 버전 작성
woowacourse-study/2022-code-review-study pull request #63
Opened 2022-04-01 18:13 UTC by byhhh2

2022-04-02 04:12 UTC, wonsss requested changes
통합본 편집을 잘 해주셨네요. 
비슷한 것을 모으고 부제를 다는 과정이 쉽지 않던데, 역시 무비~ 훌륭합니다. 
고생많으셨어요! 아~~주 어렵게 찾은 몇 가지 사소한 부분들 짚어봤는데, 확인해주시면 감사하겠습니다. 😄

2022-04-02 04:12 UTC, wonsss commented on youtube/step1/intergrated-review.md
> +  // 병합 연산자
병합 연산자보다는 더 명확한 용어인 nullish 병합 연산자라고 표현하는 게 좋을 것 같아요.
`병합 연산자` -> `nullish 병합 연산자('??')`

2022-04-02 04:12 UTC, wonsss commented on youtube/step1/intergrated-review.md
> +- 일반함수 호출에서 new.target 은 undefined
이 부분은 한 칸 더 들여쓰기해주면 좋을 것 같아요.

2022-04-02 04:12 UTC, wonsss commented on youtube/step1/intergrated-review.md
> +  - [#95] 상수에 Object.freeze를 쓰지 않으면 협업시 다른 사람들이 해당 변수의 내용을 바꾸려는 시도를 하게 될까요?
`[#95]`는 위에서 적어두었으니, 이 줄에서는 빼도 될 것 같아요.

2022-04-04 12:34 UTC, byhhh2 commented on youtube/step1/intergrated-review.md
> +  // 병합 연산자
반영했습니다~🐶

2022-04-04 12:35 UTC, byhhh2 commented on youtube/step1/intergrated-review.md
> +- 일반함수 호출에서 new.target 은 undefined
반영했습니다~🐹

2022-04-04 12:37 UTC, byhhh2 commented on youtube/step1/intergrated-review.md
> +  - [#95] 상수에 Object.freeze를 쓰지 않으면 협업시 다른 사람들이 해당 변수의 내용을 바꾸려는 시도를 하게 될까요?
반영했습니다~🐻

2022-04-04 12:38 UTC, merged